# Generated by Django 4.1.4 on 2022-12-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='manga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='manga.manga'),
            preserve_default=False,
        ),
    ]
